site_name: expAscribe

theme: 
  name: kpn
  logo: assets/2.png

site_url: https://SeabirdShore.github.io/

nav:
  - Home: index.md
  - Installation: installation.md
  - API: api.md
  - Wiki: https://external.wiki.url

  - Example:
      - Basic Tutorial: example/demo.ipynb
      - Mutation Selection: example/wetlab.ipynb

extra:
  repo_icon: 'github'
  

plugins:
  - search
  - mkdocs-jupyter
